import { writable, derived  } from 'svelte/store';
import type { Node, Edge } from '@xyflow/svelte';

export const nodes = writable<Node[]>([]);
export const edges = writable<Edge[]>([]);

export const detailInfo = writable(null);
export const isSwitchOn = writable(false);


// Writable stores for the label states
export const wasDerivedFrom_lb = writable("wasDerivedFrom");
export const wasInformedBy_lb = writable("wasInformedBy");
export const wasAttributedTo_lb = writable("wasAttributedTo");
export const actedOnBehalfOf_lb = writable("actedOnBehalfOf");
export const wasAssociatedWith_lb = writable("wasAssociatedWith");
export const wasGeneratedBy_lb = writable("wasGeneratedBy");
export const used_lb = writable("used");
export const hadMember_lb = writable("hadMember");

// Function to update labels based on switch state
export const updateLabels = (switchState: boolean) => {
    if (switchState) {
        wasDerivedFrom_lb.set("wasDerivedFrom");
        wasInformedBy_lb.set("wasInformedBy");
        wasAttributedTo_lb.set("wasAttributedTo");
        actedOnBehalfOf_lb.set("actedOnBehalfOf");
        wasAssociatedWith_lb.set("wasAssociatedWith");
        wasGeneratedBy_lb.set("wasGeneratedBy");
        used_lb.set("used");
        hadMember_lb.set("hadMember")
    } else {
        wasDerivedFrom_lb.set("Derived From");
        wasInformedBy_lb.set("Followed On");
        wasAttributedTo_lb.set("People resp.");
        actedOnBehalfOf_lb.set("Organisation assigned");
        wasAssociatedWith_lb.set("Part of Software");
        wasGeneratedBy_lb.set("Generated By");
        used_lb.set("used Dataset");
        hadMember_lb.set("Part of Collection")
    }
};