import { 
    changedPar, 
    changedUnit,  
    changedTempRes, 
    changedSpatRes, 
    changedScenario, 
    changedFormat, 
    changedSize, 
    changedGlobMod, 
    changedRegMod} from '$lib/store';

//WAS GENERATED BY
//----------------------------------------------------------------------------------------
export function findFirstEntity(generatedToUsedMap: any, usedToGeneratedMap: any) {
    // Find the first entity that is generated but not used by another
    return Array.from(generatedToUsedMap.keys()).filter(generated => {
        return !Array.from(usedToGeneratedMap.keys()).includes(generated);
    });
}
//------------------------------------------------------------
export function createEntityFlowCore(
    wasDerivedFrom: any,
    GeneratedName: string,
    UsedName: string ) 
    {
    // Create maps to store relationships
    const generatedToUsedMap = new Map<string, string[]>();
    const usedToGeneratedMap = new Map<string, string[]>();

    // Populate the maps
    for (const entry of Object.values(wasDerivedFrom)) {
        const generated = entry[GeneratedName]; //'prov:generatedEntity'
        const used = entry[UsedName]; // 'prov:usedEntity'

        // Update generatedToUsedMap
        if (!generatedToUsedMap.has(generated)) {
            generatedToUsedMap.set(generated, []);
        }
        generatedToUsedMap.get(generated)!.push(used);

        // Update usedToGeneratedMap
        if (!usedToGeneratedMap.has(used)) {
            usedToGeneratedMap.set(used, []);
        }
        usedToGeneratedMap.get(used)!.push(generated);
    }

    const startEntities = findFirstEntity (generatedToUsedMap,   usedToGeneratedMap)

    return { startEntities , generatedToUsedMap};
}
//-----------------------------------------------------------------------
const entityIdMap = new Map<string, string>();
let uniqueCounter = 0;  // Global counter for extra uniqueness

export function getEntityId(entity: string): string {
    if (!entityIdMap.has(entity)) {
        const uniqueEntityId = `${entity}${Date.now()}-${uniqueCounter}`;
        entityIdMap.set(entity, uniqueEntityId);
        uniqueCounter++; // Increment to avoid collisions
    }
    return entityIdMap.get(entity)!;
}


export function createEntityFlow(
dataset: any,
nodes: any, 
edges: any,
label: string,
swapArrow: boolean,
): void {
// Function to print all derivations starting from a given entity

// Create Entities
const { startEntities, generatedToUsedMap } = createEntityFlowCore(dataset.wasDerivedFrom, 'prov:generatedEntity', 'prov:usedEntity');

// Process all starting entities
for (let startEntity of startEntities) {
    let queue = [startEntity];

    let visited = new Set<string>();
    let yPosition = 0;

    while (queue.length > 0) {
        let currentEntity = queue.shift()!;
        if (visited.has(currentEntity)) continue;
        visited.add(currentEntity);

        
        function findCollectionForEntity(currentEntity, hadMember) {
            // Iterate through the hadMember object to find the matching collection
            const entry = Object.values(hadMember).find(member => member["prov:entity"] === currentEntity);
            return entry ? entry["prov:collection"] : "No Collection defined";
        }

        function calculateSpatialResolution(
            gridSize: [number, number], 
            upperLeft: [number, number], 
            upperRight: [number, number], 
            lowerLeft: [number, number]
        ): string {
            
            const [width, height] = gridSize;
        
            const longitudeRange = upperRight[0] - upperLeft[0]; // 52.0 - 10.0
            const latitudeRange = upperLeft[1] - lowerLeft[1];   // -5.0 - (-36.0)
        
            const lonResolution = longitudeRange / width;  // 42.0 / 84 = 0.5°
            const latResolution = latitudeRange / height;  // 31.0 / 62 = 0.5°
        
            return `${lonResolution.toFixed(1)}° x ${latResolution.toFixed(1)}°`;
        }

        let name: string | null = null;
        let unit: string | null = null;
        let extent: any | null = null;
        let collection: string | null = null;
        let regionalmodel: string | null = null;
        let globalmodel: string | null = null;
        let scenario: string | null = null;
        let format: string | null = null;
        let temporalResolution: string | null = null;
        let spatialResolution: string | null = null;
        let size: string | null = null;
        let parsedTimespans: any | null = null;
        let timestamp: string | null = null;
        let project: string | null = null;
        let experiment: string | null = null;
        let standard: string | null = null;
        let bias: string | null = null;
        let source: string | null = null;
        let institution: string | null = null;
        let domain: string | null = null;
        let contact: string | null = null;
        let tracking_id: string | null = null;
        let doi: string | null = null;
        let variant: string | null = null;

        if (dataset.entity[currentEntity]) {
            
            // EXTRACT PARAMTER NAME
            // Split the string at ", ", find the part starting with "name:", and extract the value
            name = dataset.entity[currentEntity]["tippecc_data:variable_id"];
            
            //EXTRACT UNIT
            unit = dataset.entity[currentEntity]["tippecc_data:units"];


            // EXTRACT BBOXES
            const upperLeft = dataset.entity[currentEntity]["tippecc_data:upperLeft"].split(", ").map(Number);
            const lowerRight = dataset.entity[currentEntity]["tippecc_data:lowerRight"].split(", ").map(Number);
            const lowerLeft = dataset.entity[currentEntity]["tippecc_data:lowerLeft"].split(", ").map(Number);
            const upperRight = dataset.entity[currentEntity]["tippecc_data:upperRight"].split(", ").map(Number);
            const gridSize = dataset.entity[currentEntity]["tippecc_data:size"].split(", ").map(Number);
            extent = [upperLeft[0], lowerRight[0], lowerRight[1], upperLeft[1]]

            // EXTRACT COLLECTION
            collection = findCollectionForEntity(currentEntity, dataset.hadMember);


            // EXTRACT REGIONAL MODEL TODO
            regionalmodel =  "Dummy Regional Model";//dataset.entity[currentEntity]["tippecc_data:source"];

            // EXTRACT Global MODEL
            globalmodel =  dataset.entity[currentEntity]["tippecc_data:source_id"];
            
            // EXTRACT scenario TODO
            scenario =  dataset.entity[currentEntity]["tippecc_data:scenario"] || "SSP-X";

            //EXTRACT File Format TODO
            format =  dataset.entity[currentEntity]["tippecc_data:format"] || "netCDF";

            //EXTRACT temp res
            temporalResolution =  dataset.entity[currentEntity]["tippecc_data:frequency"];

            //EXTRACT spat res
            spatialResolution = calculateSpatialResolution(gridSize, upperLeft, upperRight, lowerLeft);

            //EXTRACT File Size
            size = dataset.entity[currentEntity]["tippecc_data:file_size"]["$"];

            //TODO
            parsedTimespans = [ { start: 1910, end: 1960 }, { start: 1980, end: 2050 } ];

            //EXTRACT Timestamp
            timestamp = dataset.entity[currentEntity]["tippecc_data:creation_date"];
            
            // EXTRACT Project TODO
            project = dataset.entity[currentEntity]["tippecc_data:activity_id"];

            // EXTRACT experiment
            experiment = dataset.entity[currentEntity]["tippecc_data:experiment_id"];

            // EXTRACT Standard
            standard = dataset.entity[currentEntity]["tippecc_data:Conventions"];

            //EXTRACT Bias TODO
            bias = "Yes";

            //EXTRACT source TODO
            source = "Climate Limited-area Modelling Community (CLM-Community)";

            //EXTRACT institution
            institution = dataset.entity[currentEntity]["tippecc_data:institution"];

            //EXTRACT domain TODO
            domain = dataset.entity[currentEntity]["tippecc_data:realm"];

            //EXTRACT contact
            contact = dataset.entity[currentEntity]["tippecc_data:contact"];

            //EXTRACT tracking_id
            tracking_id = dataset.entity[currentEntity]["tippecc_data:tracking_id"];

            //EXTRACT doi
            doi = "doi:example"//dataset.entity[currentEntity]["tippecc_data:references"];

            //EXTRACT variant
            variant = dataset.entity[currentEntity]["tippecc_data:parent_variant_label"];

        } else {
            //console.warn(`Entity ${currentEntity} does not exist in dataset.entity`);
        }


        // Add node for currentEntity
        nodes.update(n => {
            const uniqueEntityId = getEntityId(currentEntity);  // Use the helper to get unique ID
            //console.log("Entity Node Id:", uniqueEntityId);
            if (!n.some(node => node.id === uniqueEntityId)) {
                //console.log(uniqueEntityId);
                
                n.push({
                    id: uniqueEntityId,
                    type: 'entityNode', // Specify the custom node type
                    data: {
                        parameter: name  || "N/A",
                        zeitspranne: parsedTimespans  || [],
                        regionalmodell: regionalmodel  || "N/A",
                        globalmodell: globalmodel  || "N/A",
                        einheit: unit  || "N/A",
                        szenario: scenario  || "N/A",
                        format: format  || "N/A",
                        resolutionZeitlich: temporalResolution  || "N/A",
                        resolutionRaeumlich: spatialResolution  || "N/A",
                        spatialExtent: extent  || "N/A",
                        //spatialExtent_orig: [0,0,0,0],
                        dateigroesse: size  || "N/A",
                        timestamp: timestamp || "N/A",
                        project: project  || "N/A",
                        experiment: experiment  || "N/A",
                        standard: standard || "N/A",
                        bias: bias  || "N/A",
                        source: source  || "N/A",
                        institution: institution || "N/A",
                        domain: domain || "N/A",
                        contact: contact || "N/A",
                        tracking_id: tracking_id || "N/A",
                        doi: doi || "N/A",
                        collection: collection  || "N/A",
                        variant: variant || "N/A"

                    },
                    position: { x: 0, y: yPosition },
                });
                yPosition += 400;       
            }
            return n;
        });

        // Add edges to connected entities
        if (generatedToUsedMap.has(currentEntity)) {
            for (const usedEntity of generatedToUsedMap.get(currentEntity)!) {

                if (!dataset.entity[usedEntity]) {

                    //console.warn(`usedEntity ${usedEntity} does not exist in dataset.entity`);

                } else {
                    
                    const name_used = dataset.entity[usedEntity]["tippecc_data:variable_id"];
                    const unit_used = dataset.entity[usedEntity]["tippecc_data:units"];
                    const temporalResolution_used =  dataset.entity[usedEntity]["tippecc_data:frequency"];
                    const upperLeft_used = dataset.entity[usedEntity]["tippecc_data:upperLeft"].split(", ").map(Number);
                    const lowerLeft_used = dataset.entity[usedEntity]["tippecc_data:lowerLeft"].split(", ").map(Number);
                    const upperRight_used = dataset.entity[usedEntity]["tippecc_data:upperRight"].split(", ").map(Number);
                    const gridSize_used = dataset.entity[usedEntity]["tippecc_data:size"].split(", ").map(Number);
                    const spatialResolution_used = calculateSpatialResolution(gridSize_used, upperLeft_used, upperRight_used, lowerLeft_used);
                    const scenario_used =  dataset.entity[usedEntity]["tippecc_data:scenario"] || "SSP-X";
                    const format_used =  dataset.entity[usedEntity]["tippecc_data:format"] || "netCDF";
                    const size_used = dataset.entity[usedEntity]["tippecc_data:file_size"]["$"];
                    const globalmodel_used =  dataset.entity[usedEntity]["tippecc_data:source_id"];
                    const regionalmodel_used =  "Dummy Regional Model";//dataset.entity[currentEntity]["tippecc_data:source"];
                    
                    if (name !== name_used) {
                        changedPar.update(set => {
                            set.add(usedEntity);
                            return new Set(set);
                        });
                    }
                    if (unit !== unit_used) {
                        changedUnit.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (temporalResolution !== temporalResolution_used) {
                        changedTempRes.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (spatialResolution !== spatialResolution_used) {
                        changedSpatRes.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (scenario !== scenario_used) {
                        changedScenario.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (format !== format_used) {
                        changedFormat.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (size !== size_used) {
                        changedSize.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (globalmodel !== globalmodel_used) {
                        changedGlobMod.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                    if (regionalmodel !== regionalmodel_used) {
                        changedRegMod.update(set => {
                            set.add(usedEntity); // Add entity ID to the set
                            return new Set(set); // Return a new Set to trigger reactivity
                        });
                    }
                }


                const source = swapArrow ? getEntityId(usedEntity) : getEntityId(currentEntity);
                const target = swapArrow ? getEntityId(currentEntity) : getEntityId(usedEntity);
                
                
                edges.update(e => {
                    console.log("added Edge");

                    e.push({
                        id: `${source}-${target}`,   
                        source: source,
                        target: target,
                        animated: false,
                        label: label,
                        type: 'default',
                        labelStyle: 'color: black; font-size: 16px; z-index: 2; pointer-events: none;'
                    });
                    return e;
                });

                // Continue traversing from the used entity
                queue.push(getEntityId(usedEntity));
            }
        }
    }
}
}

export function createActionFlow(
    dataset:any,
    nodes: any, 
    edges: any, 
    label: string,
    swapArrow: boolean
    ): void {
    // Function to print all derivations starting from a given entity

    // Create Actions (renaming for consistency)
    const { 
        startEntities: startActions, 
        generatedToUsedMap: generatedToUsedMapAction } = createEntityFlowCore(
            dataset.wasInformedBy, 
            'prov:informed', 
            'prov:informant'
        );
    
    for (let startAction of startActions) {
        let queue = [startAction];
        let visited = new Set<string>();
        let yPosition = 0;
        while (queue.length > 0) {
            let currentEntity = queue.shift()!;
            if (visited.has(currentEntity)) continue;
            visited.add(currentEntity);
            //console.log("Activity Node Id:", currentEntity);
        
            // Add node for currentEntity
            nodes.update(n => {
                if (!n.some(node => node.id === currentEntity)) {
                    n.push({
                        id: currentEntity,
                        type: 'activityNode', // Specify the custom node type
                        data: {
                            aggregateInfo: currentEntity,
        
                        },
                        position: { x: 700, y:yPosition }, // Randomized for simplicity
                    });
                    yPosition += 400;
                }
                return n;
            });
        
            // Add edges to connected entities
            if (generatedToUsedMapAction.has(currentEntity)) {
                for (const usedEntity of generatedToUsedMapAction.get(currentEntity)!) {
                    const source = swapArrow ? usedEntity : currentEntity;
                    const target = swapArrow ? currentEntity : usedEntity;
                    const sourceHandle = swapArrow ? `${usedEntity}-top` : `${currentEntity}-bottom`;
                    const targetHandle = swapArrow ? `${currentEntity}-bottom` : `${usedEntity}-top`;
                    edges.update(e => {
                        e.push({
                            id: `${usedEntity}-${currentEntity}`,
                            source: source,
                            target: target,
                            animated: false,
                            label: label,
                            type: 'default',
                            labelStyle: 'color: black; font-size: 16px; z-index: 2; pointer-events: none;',
                            sourceHandle: sourceHandle,
                            targetHandle: targetHandle
                        });
                        return e;
                    });
        
                    // Continue traversing from the used entity
                    queue.push(usedEntity);
                }
            }
        }
        }
}

//-----------------------------------------------------------------------------


export function createPeople ({
    dataset,
    nodes,
    edges,
    EdgeLabel,
    swapArrow,
    edgeStyle
}: {
    dataset: any, 
    nodes: any, 
    edges: any,
    EdgeLabel: string,
    swapArrow: boolean,
    edgeStyle: string
}) {
    const entityNodes = new Set(); 
    let yPosition = 0;

    for (const [id, member] of Object.entries(dataset.wasAttributedTo)) {
        const personId = member["prov:agent"]; // Use full person identifier (e.g., people:Franzi)
        const entity = member["prov:entity"];

        // Find organization (orgaId) from actedOnBehalfOf
        const actedOnBehalfOfEntry = Object.values(dataset.actedOnBehalfOf).find(
            (entry: any) => entry["prov:delegate"] === personId
        );

        const orgaId = actedOnBehalfOfEntry?.["prov:responsible"] || null;
        const rorid = orgaId ? dataset.agent[orgaId]?.["wd:P6782"] : null;

        // Only add the person node if it hasn't been added yet
        if (!entityNodes.has(personId)) {
            nodes.update(n => {
                n.push({
                    id: personId,
                    type: 'personNode',
                    data: { 
                        person: personId  || "N/A",
                        orga: orgaId || "N/A",
                        orcid: dataset.agent?.[personId]?.["wd:P496"] || "N/A",
                        rorid: rorid || "N/A"
                    },
                    position: { x: -600, y: yPosition },
                });
                return n;
            });
            entityNodes.add(personId);
            yPosition += 400;
        }

        // Add edge between the person and the corresponding entity
        const source = swapArrow ? entity : personId;
        const target = swapArrow ? personId : entity;
        const sourceHandle = swapArrow ? `${entity}-left` : `${personId}-right`;
        const targetHandle = swapArrow ? `${personId}-right` : `${entity}-left`;

        edges.update(e => {
            e.push({
                id: `${personId}-${entity}`,
                source: source,
                target: target,
                sourceHandle: sourceHandle,
                targetHandle: targetHandle,
                animated: false,
                label: EdgeLabel,
                style: edgeStyle,
                labelStyle: 'color: black; font-size: 16px'
            });
            return e;
        });
    }
}
//-----------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------


//ADD Nodes and Edges for Software
export function addSoftware({
    dataset,
    nodes,
    edges,
    EdgeLabel,
    IdName,
    EntityName,
    swapArrow,
    edgestyle
}: {
    dataset: any, 
    nodes: any,
    edges: any,
    EdgeLabel: string,
    IdName: string,
    EntityName: string,
    swapArrow: boolean,
    edgestyle: string
}) {
    let yPosition = 0;
    for (const member of Object.values(dataset.wasAssociatedWith)) {
        const activityId = member[IdName];
        const agentId = member[EntityName];
        
        // Ensure agent node is added if not present
        nodes.update(n => {
            if (!n.some(node => node.id === agentId)) {
                n.push({
                    id: agentId,
                    type: 'softwareNode',
                    data: {
                        software: agentId  || "N/A",
                        source: dataset.agent[agentId]["dcterms:source"]  || "N/A",
                        version: dataset.agent[agentId]["sdo:version"]  || "N/A",
                        repository: dataset.agent[agentId]["sdo:codeRepository"]  || "N/A",
                        license: dataset.agent[agentId]["sdo:license"]  || "N/A"
                     },
                    position: { x: 1200, y: yPosition }, // Adjust as needed
                });
            }
            return n;
        });
        yPosition += 400;

        // Define edge direction based on swapArrow
        const source = swapArrow ? agentId : activityId;
        const target = swapArrow ? activityId : agentId;
        const sourceHandle = swapArrow ? `${agentId}-left` : `${activityId}-right`; // Use the correct handle
        const targetHandle = swapArrow ? `${activityId}-right` : `${agentId}-left`; // Use the correct handle
        
        // Add edge between the activity and agent
        edges.update(e => {
            e.push({
                id: `${activityId}-${agentId}`,
                source: source,
                target: target, 
                sourceHandle: sourceHandle, // Assign the correct source handle
                targetHandle: targetHandle, // Assign the correct target handle
                animated: false,
                label: EdgeLabel,
                style: edgestyle,
                labelStyle: 'color: black; font-size: 16px',
            });
            return e;
        });
    }
}


// ADD EDGES ONLY
export function addEdgesOnly({
    dataset,
    edges,
    EdgeLabel,
    IdName,
    EntityName,
    swapArrow,
    style,
    labelStyle,
    handle1,
    handle2
    //edgeStyle = {} // Allow optional edge style customization
}: {
    dataset: any, 
    edges: any,
    EdgeLabel: string,
    IdName: string,
    EntityName: string,
    swapArrow: boolean,
    style: string,
    labelStyle: string,
    handle1: string,
    handle2: string
}) {
    for (const member of Object.values(dataset)) {
        const activityId = member[IdName];
        const entityId = member[EntityName];

        
        // Define edge direction based on swapArrow
        const source = swapArrow ? getEntityId(entityId) : activityId;
        const target = swapArrow ? activityId : getEntityId(entityId);
        //console.log("source and target:", source, target);
        

        // Specify the correct handles for source and target
        const sourceHandle = swapArrow ? `${entityId}-${handle1}` : `${activityId}-${handle2}`; // Use entityNode right or activityNode left
        const targetHandle = swapArrow ? `${activityId}-${handle2}` : `${entityId}-${handle1}`; // Use activityNode left or entityNode right
        //console.log(sourceHandle, targetHandle)
        
        // Add edge between activity and entity
        edges.update(e => {
            e.push({
                id: `${source}-${target}`,
                source: source,
                target: target,
                sourceHandle: sourceHandle, // Assign the correct source handle
                targetHandle: targetHandle, // Assign the correct target handle
                animated: false,
                label: EdgeLabel,
                style: style,
                labelStyle: labelStyle
            });
            return e;
        });
    }
}

