//WAS GENERATED BY
//----------------------------------------------------------------------------------------
export function findFirstEntity(generatedToUsedMap: any, usedToGeneratedMap: any) {
    // Find the first entity that is generated but not used by another
    return Array.from(generatedToUsedMap.keys()).filter(generated => {
        return !Array.from(usedToGeneratedMap.keys()).includes(generated);
    });
}
//------------------------------------------------------------
export function createEntityFlowCore(
    wasDerivedFrom: any,
    GeneratedName: string,
    UsedName: string ) 
    {
    // Create maps to store relationships
    const generatedToUsedMap = new Map<string, string[]>();
    const usedToGeneratedMap = new Map<string, string[]>();

    // Populate the maps
    for (const entry of Object.values(wasDerivedFrom)) {
        const generated = entry[GeneratedName]; //'prov:generatedEntity'
        const used = entry[UsedName]; // 'prov:usedEntity'

        // Update generatedToUsedMap
        if (!generatedToUsedMap.has(generated)) {
            generatedToUsedMap.set(generated, []);
        }
        generatedToUsedMap.get(generated)!.push(used);

        // Update usedToGeneratedMap
        if (!usedToGeneratedMap.has(used)) {
            usedToGeneratedMap.set(used, []);
        }
        usedToGeneratedMap.get(used)!.push(generated);
    }

    const startEntities = findFirstEntity (generatedToUsedMap,   usedToGeneratedMap)

    return { startEntities , generatedToUsedMap};
}
//-----------------------------------------------------------------------

export function createEntityFlow(
    dataset: any,
    entity: any, 
    nodes: any, 
    edges: any,
    label:string,
    swapArrow: boolean,
    generatedToUsedMap: Map<string, string[]>,
    nodeType: string,
    xPos:number ):void {
    // Function to print all derivations starting from a given entity
    let queue = [entity];
    let visited = new Set<string>();
    let yPosition = 0;

    while (queue.length > 0) {
        let currentEntity = queue.shift()!;
        if (visited.has(currentEntity)) continue;
        visited.add(currentEntity);

        if (nodeType == "entityNode") {
            const variables = dataset.entity[currentEntity]["cf:variables"];
        
            // EXTRACT PARAMTER NAME
            // Split the string at ", ", find the part starting with "name:", and extract the value
            const name = variables
            .split(", ")  // Split into an array by commas
            .find(part => part.startsWith("name:"))  // Find the segment starting with "name:"
            ?.split(": ")[1];  // Split by ": " and get the value after the colon
            
            //EXTRACT UNIT
            const unit = variables
            .split(", ")  // Split into an array by commas
            .find(part => part.startsWith("units:"))  // Find the segment starting with "units:"
            ?.split(": ")[1];  // Split by ": " and get the value after the colon
            
    
            //EXTRACT TIMESPAN
            function parseTimespans(timespans: string): { start: number; end: number }[] {
                if (!timespans) {
                  return [];  // Return an empty array if no timespans data is available
                }
              
                // Process the timespans string by splitting it at ", " for multiple ranges
                return timespans.split(", ").map(range => {
                  const [start, end] = range.split("-").map(Number);  // Split each range by "-" and convert to numbers
                  return { start, end };
                });
              }
            // Safe access to the timespans data
            const timespans = dataset?.entity?.[currentEntity]?.["dcterms:temporal"];
            // Parse the timespans string
            const parsedTimespans = parseTimespans(timespans);
            
            
            // EXTRACT BBOXES
            const Bboxes = dataset.entity[currentEntity]["dcterms:spatial"];
            // Regular expression to match numbers inside square brackets
            const regex = /\[([^\]]+)\]/g;
            const matches = [...Bboxes.matchAll(regex)]; // Get all matches
            // Extract numbers from matches and convert them to arrays
            const boundingBoxes = matches.map(match => match[1].split(', ').map(Number));
            const extent = boundingBoxes[0]
            const extent_orig = boundingBoxes[1]
    
    
            // EXTRACT COLLECTION
            function findCollectionForEntity(currentEntity, hadMember) {
                // Iterate through the hadMember object to find the matching collection
                const entry = Object.values(hadMember).find(member => member["prov:entity"] === currentEntity);
                return entry ? entry["prov:collection"] : "No Collection defined";
            }
            const collection = findCollectionForEntity(currentEntity, dataset.hadMember);
    
            
            const regionalmodel =  dataset.entity[currentEntity]["tippecc:regionalmodel"];
            const globalmodel =  dataset.entity[currentEntity]["tippecc:globalmodel"];
            const scenario =  dataset.entity[currentEntity]["tippecc:scenario"];
            const format =  dataset.entity[currentEntity]["datacite:format"];
            const temporalResolution =  dataset.entity[currentEntity]["dcat:temporalResolution"];
            const spatialResolution = dataset.entity[currentEntity]["dcat:spatialResolutionInMeters"]["$"];
            const size = dataset.entity[currentEntity]["datacite:size"];
    
    
            // Add node for currentEntity
            nodes.update(n => {
                if (!n.some(node => node.id === currentEntity)) {
                    n.push({
                        id: currentEntity,
                        type: nodeType,
                        data: {                         
                            parameter: name,
                            zeitspranne: parsedTimespans,
                            regionalmodell: regionalmodel,
                            globalmodell: globalmodel,
                            einheit: unit,
                            szenario: scenario,
                            format: format,
                            resolutionZeitlich: temporalResolution,
                            resolutionRaeumlich: spatialResolution,
                            spatialExtent: extent,
                            spatialExtent_orig: extent_orig,
                            dateigroesse: size,
                            timestamp: dataset.entity[currentEntity]["prov:generatedAtTime"],
                            project: dataset.entity[currentEntity]["sdo:project"],
                            experiment: dataset.entity[currentEntity]["tippecc:experiment"],
                            standard: dataset.entity[currentEntity]["cf:standard"],
                            bias: dataset.entity[currentEntity]["tippecc:bias"],
                            source: dataset.entity[currentEntity]["dcterms:publisher"],
                            institution: dataset.entity[currentEntity]["dcterms:creator"],
                            domain: dataset.entity[currentEntity]["tippecc:domain"],
                            contact: dataset.entity[currentEntity]["tippecc:contact"],
                            tracking_id: dataset.entity[currentEntity]["esgf_portal:tracking_id"],
                            doi: dataset.entity[currentEntity]["dcterms:identifier"],
                            collection: collection 
                        
                        },
                        position: { x: xPos, y: yPosition },
                    });
                    yPosition += 400;
                }
                return n;
            });
    
        }

        if (nodeType == "activityNode") {
            // Add node for currentEntity
            nodes.update(n => {
                if (!n.some(node => node.id === currentEntity)) {
                    n.push({
                        id: currentEntity,
                        type: nodeType,
                        data: { label: currentEntity },
                        position: { x: xPos, y: yPosition },
                    });
                    yPosition += 400;
                }
                return n;
            });
            
        }

        // Get all entities that this one was derived from
        if (generatedToUsedMap.has(currentEntity)) {
            for (const usedEntity of generatedToUsedMap.get(currentEntity)!) {
                // Add edge between the current entity and the used entity
                const source = swapArrow ? usedEntity : currentEntity;
                const target = swapArrow ? currentEntity : usedEntity;
                const sourceHandle = swapArrow ? `${usedEntity}-top` : `${currentEntity}-bottom`;
                const targetHandle = swapArrow ? `${currentEntity}-bottom` : `${usedEntity}-top`;
                edges.update(e => {
                    e.push({
                        id: `${usedEntity}-${currentEntity}`,
                        source: source,
                        target: target,
                        animated: false,
                        label: label,
                        type: "default",
                        labelStyle: "color: black; font-size: 16px;",
                        sourceHandle: sourceHandle,
                        targetHandle: targetHandle
                    });
                    return e;
                });

                // Continue traversing from the used entity
                queue.push(usedEntity);
            }
        }
    }    
}
//-----------------------------------------------------------------------------

// ADD FLOW
export function createFlow ({
    data,
    dataset,
    nodes,
    edges,
    EdgeLabel,
    IdName,
    EntityName,
    swapArrow,
    edgeStyle,
    nodeType,
    xPos
}: {
    data:any,
    dataset: any, 
    nodes: any, 
    edges: any,
    EdgeLabel: string,
    IdName: string,
    EntityName: string,
    swapArrow: boolean,
    edgeStyle: string,
    nodeType: string,
    xPos:number
}) {
    // Process hadMember to create collections
    const entityNodes = new Set(); // Keep track of added collection nodes
    let yPosition = 0;
    for (const [id, member] of Object.entries(dataset)) {
        const Id = member[IdName];
        const entity = member[EntityName];

        if (nodeType == "personNode") {
            
            // Only add the collection node if it hasn't been added yet
            if (!entityNodes.has(Id)) {
                // Add collection node
                nodes.update(n => {
                    n.push({
                        id: Id,
                        type: nodeType,
                        data: {                         
                            person: Id,
                            orga: "N/A", //orgaId
                            orcid: data.agent?.[Id]?.["orcid:identifier"] || "N/A",
                            rorid: "N/A"  //rorid
                        },
                        position: { x: xPos, y:yPosition }, // Adjust position as needed
                    });
                    
                    return n;
                });
                yPosition += 400;
                entityNodes.add(Id); // Mark this entity as added
            }

        }

        if (nodeType == "orgaNode") {
            // Find organization (orgaId) from actedOnBehalfOf
            const actedOnBehalfOfEntry = Object.values(data.actedOnBehalfOf).find(
                (entry: any) => entry["prov:delegate"] === entity
            );

            const orgaId = actedOnBehalfOfEntry?.["prov:responsible"] || null;
            const rorid = orgaId ? data.agent[orgaId]?.["ror:identifier"] : null;
            
            // Only add the collection node if it hasn't been added yet
            if (!entityNodes.has(Id)) {
                // Add collection node
                nodes.update(n => {
                    n.push({
                        id: Id,
                        type: nodeType,
                        data: {                         
                            person: "N/A", //entity,
                            orga: Id || "N/A",
                            orcid: "N/A", //data.agent?.[entity]?.["orcid:identifier"] ||
                            rorid: rorid || "N/A" 
                        },
                        position: { x: xPos, y:yPosition }, // Adjust position as needed
                    });
                    
                    return n;
                });
                yPosition += 400;
                entityNodes.add(Id); // Mark this entity as added
            }

        }

        if (nodeType == "orgaNode") {
            // Find organization (orgaId) from actedOnBehalfOf
            const actedOnBehalfOfEntry = Object.values(data.actedOnBehalfOf).find(
                (entry: any) => entry["prov:delegate"] === entity
            );

            const orgaId = actedOnBehalfOfEntry?.["prov:responsible"] || null;
            const rorid = orgaId ? data.agent[orgaId]?.["ror:identifier"] : null;
            
            // Only add the collection node if it hasn't been added yet
            if (!entityNodes.has(Id)) {
                // Add collection node
                nodes.update(n => {
                    n.push({
                        id: Id,
                        type: nodeType,
                        data: {                         
                            person: "N/A", //entity,
                            orga: Id || "N/A",
                            orcid: "N/A", //data.agent?.[entity]?.["orcid:identifier"] ||
                            rorid: rorid || "N/A" 
                        },
                        position: { x: xPos, y:yPosition }, // Adjust position as needed
                    });
                    
                    return n;
                });
                yPosition += 400;
                entityNodes.add(Id); // Mark this entity as added
            }

        }
        if (nodeType === "orgaNode" || nodeType === "collectionNode") {
            // Find organization (orgaId) from actedOnBehalfOf
            const actedOnBehalfOfEntry = Object.values(data.actedOnBehalfOf).find(
                (entry: any) => entry["prov:delegate"] === entity
            );

            const orgaId = actedOnBehalfOfEntry?.["prov:responsible"] || null;
            const rorid = orgaId ? data.agent[orgaId]?.["ror:identifier"] : null;
            
            // Only add the collection node if it hasn't been added yet
            if (!entityNodes.has(Id)) {
                // Add collection node
                nodes.update(n => {
                    n.push({
                        id: Id,
                        type: nodeType,
                        data: {                         
                            person: "N/A", //entity,
                            orga: Id || "N/A",
                            orcid: "N/A", //data.agent?.[entity]?.["orcid:identifier"] ||
                            rorid: rorid || "N/A" 
                        },
                        position: { x: xPos, y:yPosition }, // Adjust position as needed
                    });
                    
                    return n;
                });
                yPosition += 400;
                entityNodes.add(Id); // Mark this entity as added
            }

        }


        // Add edge between the collection and the corresponding entity
        const source = swapArrow ? entity : Id;
        const target = swapArrow ? Id : entity;

        const sourceHandle = swapArrow ? `${entity}-left` : `${Id}-right`;
        const targetHandle = swapArrow ? `${Id}-right` : `${entity}-left`;
        edges.update(e => {
            e.push({
                id: `${Id}-${entity}`,
                source:source,
                target:target,
                animated: false,
                label: EdgeLabel,
                style: edgeStyle,
                labelStyle: "color: black; font-size: 16px;",
                sourceHandle: sourceHandle,
                targetHandle: targetHandle
            });
            return e;
        });
    }
}
//-----------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------



//ADD Nodes and Edges for Software
export function addSoftware({
    dataset,
    data,
    nodes,
    edges,
    EdgeLabel,
    IdName,
    EntityName,
    swapArrow,
    edgestyle,
    nodeType,
    xPos
}: {
    dataset: any, 
    data: any,
    nodes: any,
    edges: any,
    EdgeLabel: string,
    IdName: string,
    EntityName: string,
    swapArrow: boolean,
    edgestyle: string,
    nodeType: string,
    xPos:number
}) {
    let yPosition = 0;
    for (const member of Object.values(dataset)) {
        const activityId = member[IdName];
        const agentId = member[EntityName];

        
        // Ensure agent node is added if not present
        nodes.update(n => {
            if (!n.some(node => node.id === agentId)) {
                n.push({
                    id: agentId,
                    type: nodeType,
                    data: {                         
                        software: agentId,
                        source: data.agent[agentId]["dcterms:source"],
                        version: data.agent[agentId]["sdo:version"],
                        repository: data.agent[agentId]["sdo:codeRepository"],
                        license: data.agent[agentId]["sdo:license"] 
                    },
                    position: { x: xPos, y: yPosition }, // Adjust as needed
                });
                yPosition += 400;
            }
            return n;
        });

        // Define edge direction based on swapArrow
        const source = swapArrow ? agentId : activityId;
        const target = swapArrow ? activityId : agentId;

        const sourceHandle = swapArrow ? `${agentId}-left` : `${activityId}-right`;
        const targetHandle = swapArrow ? `${activityId}-right` : `${agentId}-left`;
        
        // Add edge between the activity and agent
        edges.update(e => {
            e.push({
                id: `${activityId}-${agentId}`,
                source: source,
                target: target,
                animated: false,
                label: EdgeLabel,
                style: edgestyle,
                labelStyle: "color: black; font-size: 16px;" ,
                sourceHandle: sourceHandle,
                targetHandle: targetHandle
            });
            return e;
        });
    }
}


// ADD EDGES ONLY
export function addEdgesOnly({
    dataset,
    edges,
    EdgeLabel,
    IdName,
    EntityName,
    swapArrow,
    style,
    labelStyle,
    handle1,
    handle2
    //edgeStyle = {} // Allow optional edge style customization
}: {
    dataset: any, 
    edges: any,
    EdgeLabel: string,
    IdName: string,
    EntityName: string,
    swapArrow: boolean,
    style: string,
    labelStyle: string,
    handle1: string,
    handle2: string
}) {
    for (const member of Object.values(dataset)) {
        const activityId = member[IdName];
        const entityId = member[EntityName];
        
        // Define edge direction based on swapArrow
        const source = swapArrow ? entityId : activityId;
        const target = swapArrow ? activityId : entityId;

        // Specify the correct handles for source and target
        const sourceHandle = swapArrow ? `${entityId}-${handle1}` : `${activityId}-${handle2}`; // Use entityNode right or activityNode left
        const targetHandle = swapArrow ? `${activityId}-${handle2}` : `${entityId}-${handle1}`; // Use activityNode left or entityNode right
        
        // Add edge between activity and entity
        edges.update(e => {
            e.push({
                id: `${activityId}-${entityId}`,
                source: source,
                target: target,
                animated: false,
                label: EdgeLabel,
                style: style,
                labelStyle: labelStyle,
                sourceHandle: sourceHandle,
                targetHandle: targetHandle
            });
            return e;
        });
    }
}

